# Generated by Django 4.2.7 on 2023-11-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messdeck', '0008_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hostel',
            new_name='mess',
        ),
    ]
