# Generated by Django 4.2.7 on 2023-11-30 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messdeck', '0009_rename_hostel_profile_mess'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfast',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
