# Generated by Django 4.2.7 on 2023-11-30 09:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messdeck', '0011_attendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='attendance',
            new_name='attend',
        ),
    ]
